### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by christianbundy** [mmckegg/micro-css#5]
Hey @mmckegg, would you be open to adding a license to this repo? :upside_down_face:

**Comment by mmckegg** [comment]
@christianbundy
Weird, thought it did. Happy with something permissive on this. MIT, BSD, or something. What are the cool kids using these days?

**Comment by christianbundy** [comment]
:man_shrugging:

I'm happy with anything. I'll usually go between MIT and ISC because I don't care enough to change the npm/yarn defaults, but there's also the ultra-permissive [0BSD](https://en.wikipedia.org/wiki/BSD_licenses#0-clause_license_(%22Zero_Clause_BSD%22)) option (just avoid reading about the naming history if you value your sanity).

**Comment by mmckegg** [comment]
Closed via https://github.com/mmckegg/micro-css/commit/4a1a117997bb334642efb29a35f954e89398efa4

**Comment by christianbundy** [comment]
Thank you!
